# Generated by Django 2.1.7 on 2019-04-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schulnotenerfassung', '0002_auto_20190416_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
