# Generated by Django 2.2 on 2019-04-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faecher',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('fach_name', models.CharField(max_length=200, unique=True, verbose_name='Fach Bezeichnung')),
            ],
            options={
                'verbose_name': 'Fach',
                'verbose_name_plural': 'Faecher',
            },
        ),
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('k_id', models.AutoField(primary_key=True, serialize=False)),
                ('jahrgang', models.IntegerField(verbose_name='Jahrgang')),
                ('name', models.CharField(max_length=200, verbose_name='Klassen Bezeichnung')),
            ],
            options={
                'verbose_name': 'Klasse',
                'verbose_name_plural': 'Klasse',
                'unique_together': {('jahrgang', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lehrer',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lehrer',
                'verbose_name_plural': 'Lehrer',
            },
        ),
        migrations.CreateModel(
            name='Unterrichts_Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Faecher', verbose_name='Fach')),
                ('k_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Klasse', verbose_name='Klasse')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Lehrer', verbose_name='Lehrer')),
            ],
            options={
                'verbose_name': 'Unterrichts Fach',
                'verbose_name_plural': 'Unterrichts Faecher',
                'unique_together': {('f_id', 'l_id', 'k_id')},
            },
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('k_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schulnotenerfassung.Klasse', verbose_name='Klasse')),
            ],
            options={
                'verbose_name': 'Schueler',
                'verbose_name_plural': 'Schueler',
            },
        ),
        migrations.CreateModel(
            name='Noten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Schueler', verbose_name='Schueler')),
                ('u_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Unterrichts_Fach', verbose_name='Unterrichts Fach')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Noten',
                'unique_together': {('s_id', 'u_id')},
            },
        ),
    ]
