# Generated by Django 2.1.5 on 2019-03-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faecher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField()),
                ('fach_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_id', models.IntegerField()),
                ('jahrgang', models.DateField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lehrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Noten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Faecher')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Lehrer')),
            ],
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unterrichts_Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Faecher')),
                ('k_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Klasse')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Lehrer')),
            ],
        ),
        migrations.AddField(
            model_name='noten',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schulnotenerfassung.Schueler'),
        ),
    ]
